apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-todo-app-1
  description: A simple Go app
  annotations:
    github.com/project-slug: siddarthsurana-org/go-todo-app-1
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: siddarthsurana
