site_name: go-todo-app-1
repo_url: https://github.com/siddarthsurana/go-todo-app-1
site_description: A brief description of my project.
site_author: Siddarth Surana

# Navigation structure
nav:
  - Overview:
    - Getting started: docs/index.md

plugins:
  - techdocs-core